### ISSUE TITLE
Countdown animation does not appear on disarm dialog when not using Alarmo

### ISSUE THREAD

**Issue by repjas** [thanksmister/android-mqtt-alarm-panel#164]
**Is your feature request related to a problem? Please describe.**
I have the app always running on a phone that is mounted to a wall. Now and then the app completely closes and I have to manually start it up again.

**Describe the solution you'd like**
Is it possible to add some sort of auto restart to the app?

Running on a Oneplus 3T.

**Comment by thanksmister** [comment]
Well I would first try to see why the app is crashing but there is already a feature to restart the app after a crash.  Maybe you do not have the latest version, check the Github repository.    To help further, I would need to know your version of the app you are running and the device Android version.

**Comment by repjas** [comment]
I have version 0.8.9 which is the latest in the Play Store. Would you advise me to download the APK from GitHub? I thought these were less stable versions?

I run the app on Android 9. OxygenOS 9.0.6

**Comment by thanksmister** [comment]
Yeah I think it would be good to update as there was an MQTT issue in the older app.

**Comment by repjas** [comment]
I downloaded the new latest version.

Bad news: it crashes when I click on advanced alarm settings.
Good news: it auto restarts after the crash.

Also, I don't see anymore a countdown timer when entering the code. This was useful in the older versions. Is this a conscious choice or a bug? Perhaps it has to do with the advanced alarm settings that I cannot open?

**Comment by thanksmister** [comment]
You did not tell me which version you have.   The latest version is v1.1.1-beta.3 from Github.

**Comment by repjas** [comment]
Apologies. With the latest version I meant that one: V1.1.1-beta.3. the latest GitHub release.

**Comment by thanksmister** [comment]
There must be an upgrade issue, I cannot reproduce the crash on new install.  Try uninstalling and reinstalling the app version, under advanced settings are delay times for setting the code which should display the countdown timer.

**Comment by thanksmister** [comment]
The countdown timer should be displayed if you initiated the alarm mode from the application.  It will be a generic screen if the alarm was initiated from HA.  This is because it does not know the alarm mode, just that its changing modes.   

We now use Alarmo integration for the alarm which provides better states and also provides the delay times remotely from the server.   

But this is optional, you should still be able to work with the MQTT manual component and if you set the alarm to "away" with a 60 second delay, this should still display in the app on the main screen, if it does not, then that is a bug.

**Comment by thanksmister** [comment]
I see an issue when setting the away countdown clock, will issue a fix in next release.   However I still don't have enough information to fix the crash on advanced setting screen.  I will address that as soon as I have some more information.

**Comment by thanksmister** [comment]
I published a new version with a fix for both issues, please test https://github.com/thanksmister/android-mqtt-alarm-panel/releases/tag/v1.1.1.4

**Comment by repjas** [comment]
I un-installed the app and re-installed. The advanced setting screen no longer crashes. You were right that it didn't work with updating, but works on a fresh install.

However, I still don't get the countdown timer.
The case:
door opens --> screen with code entry appears, but without countdown timer --> screen shows disarmed after succesful entry.

I use version app version 1.1.1.4 via MQTT with Home Assistant MQTT manual alarm. I do not use Alarmo.
I have set the pending seconds in the advanced settings.

Did I perhaps miss something, or is there still a bug in the countdown timer? All seems functional except for the lack of countdown timer during code entry. I have tried setting the alarm from both the app and Home Assistant.

Thanks for your support so far.

**Comment by thanksmister** [comment]
For now you will have to use the app with the current behavior until I have a chance to test it and issue an update.

**Comment by repjas** [comment]
Okay. Thanks again for this great app and your active support.

**Comment by thanksmister** [comment]
You can try this one: https://github.com/thanksmister/android-mqtt-alarm-panel/releases/tag/v1.1.1.5

**Comment by repjas** [comment]
I just switched to Alarmo because it seems like a nice system.

Does it help you if I reconfigure the app and test it with manual mqtt panel?

**Comment by thanksmister** [comment]
No, continue with Alarmo, it's a nicer integration.  There will be other users using the older mqtt manual component.

**Comment by thanksmister** [comment]
I am closing this issue as fixed.
